project:
  type: website

website:
  title: "Brian McNamara Data Analytics Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bmac1313
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/in/brianmcgis/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

